#!/bin/bash

# Inspector Twin - Quick Reference Commands
# Copy and paste commands directly from this file

echo "📚 Inspector Twin - Command Reference"
echo "====================================="
echo ""
echo "INSTALLATION & STARTUP"
echo "---"
echo "cd /Users/nathanbrown-bennett/Inspector/inspectortwin"
echo "npm install                    # Install dependencies (2-3 min)"
echo "./run_dev.sh                   # Start development (30-45 sec)"
echo ""

echo "DEVELOPMENT"
echo "---"
echo "npm run build                  # Build all packages"
echo "npm run build --workspaces     # Build with workspace filtering"
echo "npm test --workspaces          # Run all tests"
echo "npm run watch --workspaces     # Watch mode for rebuilding"
echo "npm run clean --workspaces     # Clean all build output"
echo ""

echo "TESTING"
echo "---"
echo "npm test --workspace=@inspectortwin/policy-dsl     # Test DSL"
echo "npm test --workspace=@inspectortwin/core-sim       # Test simulation"
echo "npm run test:watch --workspaces                    # Watch mode"
echo ""

echo "VERIFICATION"
echo "---"
echo "./verify.sh                    # Check project integrity"
echo ""

echo "PRODUCTION"
echo "---"
echo "./scripts/build.sh                              # Build for current platform"
echo "npm run package --workspace=apps/desktop        # Package current platform"
echo "npm run package:mac --workspace=apps/desktop    # Package macOS (.dmg)"
echo "npm run package:win --workspace=apps/desktop    # Package Windows (.exe)"
echo "npm run package:linux --workspace=apps/desktop  # Package Linux (.AppImage)"
echo ""

echo "TROUBLESHOOTING"
echo "---"
echo "kill -9 \$(lsof -t -i:5173)                      # Kill port 5173"
echo "rm ~/.local/share/inspectortwin/database.sqlite # Reset database"
echo "npm install --force                             # Force reinstall deps"
echo "npm run clean && npm install                    # Full clean install"
echo ""

echo "VIEWING LOGS"
echo "---"
echo "tail -f ~/.local/share/inspectortwin/logs/main.log  # Tail main process"
echo "# Or open DevTools in Electron: Ctrl+Shift+I (Windows/Linux) or Cmd+Option+I (Mac)"
echo ""

echo "USEFUL PATHS"
echo "---"
echo "Project root:     /Users/nathanbrown-bennett/Inspector/inspectortwin/"
echo "Source code:      packages/ and apps/"
echo "Database:         ~/.local/share/inspectortwin/database.sqlite"
echo "Reports:          ~/Documents/InspectorTwin/"
echo "Logs:             ~/.local/share/inspectortwin/logs/"
echo ""

echo "DOCUMENTATION"
echo "---"
echo "START HERE:       Open QUICKSTART.md (5-minute guide)"
echo "User Guide:       Open README.md (feature overview)"
echo "Architecture:     Open IMPLEMENTATION.md (technical details)"
echo "File Inventory:   Open MANIFEST.md (what was built)"
echo "Project Status:   Open STATUS.md (completion report)"
echo "All Guides:       Open INDEX.md (navigation hub)"
echo ""

echo "QUICK WORKFLOWS"
echo "---"
echo "First Time Setup:"
echo "  1. cd /Users/nathanbrown-bennett/Inspector/inspectortwin"
echo "  2. npm install"
echo "  3. ./run_dev.sh"
echo "  4. Create a project in the UI"
echo "  5. Design topology, run simulation, generate report"
echo ""

echo "Development Iteration:"
echo "  1. Make code changes"
echo "  2. Save file (Vite auto-reloads React components)"
echo "  3. For backend changes: npm run build"
echo "  4. UI updates automatically"
echo ""

echo "Testing:"
echo "  1. npm test --workspaces          # Run all tests"
echo "  2. npm run test:watch             # Watch mode during development"
echo "  3. Review test files for patterns: policy.test.ts, validation.test.ts"
echo ""

echo "Building for Production:"
echo "  1. ./scripts/build.sh             # Build everything"
echo "  2. npm run package --workspace=apps/desktop  # Create installer"
echo "  3. Output in apps/desktop/dist/"
echo ""

echo "====================================="
echo "🚀 Ready to build your digital twin!"
